### ISSUE TITLE
Video Settings don't work

### ISSUE THREAD

**Issue by Bob-Hoogenboom** [Bob-Hoogenboom/Warship#50]
ResolutionController.cs
ScreenSizeController.cs

Maybe a variable isn't assigned or something isnt quite right with the settings in general.
It simply doesn't change anything

**Comment by DiegoR03** [comment]
There was no event assigned in the editor.
Prefab (Main Menu / In-game Panel) -> Option Panel Object -> Video Panel Object -> Resolution/Screen size Object -> Dropdown Object. In the dropdown object you create an event, and in this event you use the Main Menu/In-game object. From here you assign the ScreensizeController.setScreenSize or the ResolutionController.SetResoltion (Dynamic Int).
